case = "ignore"
end-markers = "?!:."
features = "collate-link-defs,outsource-inline-links,never-break-html,never-break-code-spans"
ignores = ""
lang = "ac"
max-width = 80
suppressions = ""
upstream-command = ""
upstream = ""
upstream-separator= ""
